### ISSUE TITLE
Breaks with latest versions of node.js

### ISSUE THREAD

**Issue by pierodamafalda** [Mitranim/gulp-html-to-js#6]
This is a wonderful plug-in and worked for me in the previous versions of node.js But now with the latest versions of node.js breaks the pipe with an error on path:<br>
Path must be a string<br>
Have you tried the plug-in with versions from 8.12.0 onwards?<br>

**Comment by mitranim** [comment]
Hello there, glad to see some interest.

The error message probably originates at [this line](https://github.com/Mitranim/gulp-html-to-js/blob/c419788612ea1bc9e1421ede44e7aa3d4003be26/gulp-html-to-js.js#L45) when calling `path.join`. My system currently uses Node v8.11.3, which has the same path validation. If this error occurs on Node v8.12.0, it should also occur on v8.11.3. However, the tests pass for me, indicating that the problem might be elsewhere.

Would be nice if you listed the stacktrace, the gulp version, and the line from the gulp task preceding this plugin. Also, please try to find the vinyl version; historically, vinyl incompatibilities have been the №1 source of issues.

**Comment by pierodamafalda** [comment]
Hello thank you for caring. Yes the stacktrace points to Vinyl. I'll try to upgrade it.
My gulp version is 3.9.0
the task is:
gulp.task('templates', function() {
  return gulp.src('./src/templates/*.html')
    .pipe(htmlToJs({ concat: 'pwf-templates.js'}))
    .pipe(gulp.dest('./dist/temp')
    );
});

STACKTRACE

[20:46:51] Starting 'templates'...
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:211:7)
    at DestroyableTransform.saveFile [as _transform] (C:\PROGETTI\Cliente - RegioneER\pwf-dev-gulp\node_modules\vinyl-fs\lib\dest\index.js:36:26)
    at DestroyableTransform.Transform._read (C:\PROGETTI\Cliente - RegioneER\pwf-dev-gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\PROGETTI\Cliente - RegioneER\pwf-dev-gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\PROGETTI\Cliente - RegioneER\pwf-dev-gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at clearBuffer (C:\PROGETTI\Cliente - RegioneER\pwf-dev-gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:316:5)
    at onwrite (C:\PROGETTI\Cliente - RegioneER\pwf-dev-gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:274:7)
    at WritableState.onwrite (C:\PROGETTI\Cliente - RegioneER\pwf-dev-gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:106:5)
    at afterTransform (C:\PROGETTI\Cliente - RegioneER\pwf-dev-gulp\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:104:5)

**Comment by pierodamafalda** [comment]
Solved. I was using gulp-html-to-js version 0.0.6 
Upgrading to 0.0.7 solved the issue.
Now I have:
    "gulp": "^3.9.1",
    "gulp-html-to-js": "0.0.7",
    "vinyl-fs": "^3.0.3",
 node.js 8.12

Thanks you very much for the patience and for the plug-in.
